use_frameworks!

platform :ios, '9.0'

target 'zjNetWork_Example' do
  pod 'zjNetWork', :path => '../'

  target 'zjNetWork_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
